integrating og workflow with this one

diff --git a/.github/workflows/packagev2.yml b/.github/workflows/packagev2.yml
--- a/.github/workflows/packagev2.yml
+++ b/.github/workflows/packagev2.yml
@@ -10,6 +10,11 @@ on:
 jobs:
   generate_conda_packd_envs:
     name: conda-pack'd env with Python ${{ inputs.version }}
+    strategy:
+      fail-fast: false
+      matrix:
+        repos: [ { org: "NSLS-II-CSX", repo: "profile_collection", branch: "master", profile_branch: "qserver", beamline_acronym: "csx" },
+                 { org: "NSLS-II-SRX", repo: "profile_collection", branch: "master", profile_branch: "master", beamline_acronym: "srx" } ]
     runs-on: ubuntu-latest
     outputs:
       test_conda_packed_name: ${{ env.TEST_ENV_NAME }}
@@ -84,9 +89,115 @@ jobs:
           echo $MAMBA_ROOT_PREFIX
           ls
         #original line 1: set -vxeuo pipefail
-      - run: |
-          eval "$(conda shell.bash hook)"
-          conda activate $MAMBA_ROOT_PREFIX/envs/${{ env.CONDA_PACK_ENV_NAME }}
+      - name: Cloning Remote Repositories
+        run: |
+          mkdir "${{matrix.repos.repo}}"
+          git clone -b ${{matrix.repos.branch}} "https://github.com/${{matrix.repos.org}}/${{matrix.repos.repo}}" "${{matrix.repos.repo}}"
+      - name: Configuring defaults (pyOlog, databroker, and kafka)
+        run: |
+          echo "pyOlog config:"
+          wget https://raw.githubusercontent.com/NSLS-II/profile-collection-ci/master/configs/pyOlog.conf -O $HOME/.pyOlog.conf
+          cat $HOME/.pyOlog.conf
+
+          echo "Classic databroker v0/v1 config:"
+          databroker_conf_dir="$HOME/.config/databroker"
+          beamline_acronym="${BEAMLINE_ACRONYM,,}"
+          databroker_bl_conf="${beamline_acronym}.yml"
+          mkdir -v -p ${databroker_conf_dir}
+          wget https://raw.githubusercontent.com/NSLS-II/profile-collection-ci/master/configs/databroker.yml -O ${databroker_conf_dir}/_legacy_config.yml
+          cp -v ${databroker_conf_dir}/_legacy_config.yml ${databroker_conf_dir}/${databroker_bl_conf}
+          cat ${databroker_conf_dir}/_legacy_config.yml
+          cat ${databroker_conf_dir}/${databroker_bl_conf}
+
+          echo "Tiled profile config:"
+          tiled_profiles_dir="$HOME/.config/tiled/profiles/"
+          mkdir -v -p "${tiled_profiles_dir}"
+          sed 's/^  //' << EOF > "${tiled_profiles_dir}/profiles.yml"
+          ${beamline_acronym:-local}:
+            direct:
+              authentication:
+                allow_anonymous_access: true
+              trees:
+              - tree: databroker.mongo_normalized:Tree.from_uri
+                path: /
+                args:
+                  uri: mongodb://localhost:27017/metadatastore-local
+                  asset_registry_uri: mongodb://localhost:27017/asset-registry-local
+          EOF
+            cat ${tiled_profiles_dir}/profiles.yml
+
+            echo "Kafka config:"
+            sed 's/^  //' << EOF > kafka.yml
+            ---
+              abort_run_on_kafka_exception: false
+              bootstrap_servers:
+                - localhost:9092
+              runengine_producer_config:
+                security.protocol: PLAINTEXT
+          EOF
+
+            echo "SUDO: Placing kafka config in /etc/bluesky"
+            sudo mkdir -v -p /etc/bluesky/
+            sudo mv -v kafka.yml /etc/bluesky/kafka.yml
+            cat /etc/bluesky/kafka.yml
+      - name: Setup Ipython Test Profile
+        env:
+          PROFILE_REPO: "https://github.com/${{matrix.repos.org}}/${{matrix.repos.repo}}.git"
+          PROFILE_BRANCH: "${{matrix.repos.profile_branch}}"
+        run: |
+          echo "Preparing test profile"
+          rm -rfv profile_collection
+            git clone "$PROFILE_REPO" profile_collection
+            (
+              cd profile_collection
+              git checkout "$PROFILE_BRANCH"
+              rm -rfv ~/.ipython/profile_${{env.PROFILE_NAME}}/
+              mkdir -pv ~/.ipython/profile_${{env.PROFILE_NAME}}/
+              cp -rv startup ~/.ipython/profile_${{env.PROFILE_NAME}}/
+            )
+      - name: Set Up Ipython
+        run: pip install ipython
+      - name: Creating Ipython Profile
+        run: ipython profile create ${{env.PROFILE_NAME}}
+      - name: Configuring Redis
+        uses: shogo82148/actions-setup-redis@v1
+        with:
+          redis-version: latest
+      - name: Configuring Mongo
+        uses: supercharge/mongodb-github-action@1.11.0
+        with:
+          mongodb-version: '4.4'
+      - name: Performing Beamline Actions
+        env:
+          BEAMLINE_ACRONYM: ${{matrix.repos.beamline_acronym}}
+        run: |
+          echo "Performing beamline-specific tasks..."
+          cfg_dir="/nsls2/data/$BEAMLINE_ACRONYM/shared/config"
+          if [[ ! -d "$cfg_dir" ]]; then
+            sudo mkdir -v -p "$cfg_dir" ||
+            (
+              echo "Error: Couldn't create dir: $cfg_dir"
+              exit 1
+            )
+          fi
+      - name: Setting up Blackhole IOC
+        run: |
+          python3 -m pip install -U caproto
+          echo | python3 -m caproto.ioc_examples.pathological.spoof_beamline &
+          trap 'kill -SIGINT %1; echo exiting...' EXIT
+          sudo ln -svf caproto-repeater "/bin/caRepeater"
+      - name: Checking Blackhole IOC PV's
+        run: |
+          sudo pip install supervisor
+          chmod +x supervisor/start_supervisor.sh
+          supervisor/start_supervisor.sh status
+      - name: Start IPython
+        run: |
+          conda activate "${{ env.CONDA_PREFIX }}/envs/${{ env.CONDA_ENV_NAME }}"
+          for tiled_profile_name in nsls2 ${{matrix.repos.beamline_acronym}}; do
+            tiled profile create --name $tiled_profile_name https://127.0.0.1:8000
+          done
+          ipython --profile ${{env.PROFILE_NAME}}
 #      - name: Export files
 #        run: |
 #          set -vxeo pipefail
